name: Frontend Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Go to frontend
        working-directory: front/front
        run: pwd

      - name: Install dependencies
        working-directory: front/front
        run: npm install

      - name: Build frontend
        working-directory: front/front
        run: npm run build